My Project: HAL/Buffer_Circ.h File Reference
Buffer_Circ.h File Reference
Data Structures
struct TFile
Macros
#define TailleFile 128
Typedefs
typedef struct TFile BC
Functions
void InitBC (BC *bc)
int FileVide (BC *bc)
int FilePleine (BC *bc)
char Defiler (BC *bc)
void Enfiler (BC *bc, char c)
Macro Definition Documentation
#define TailleFile 128
Definition at line 1 of file Buffer_Circ.h.
Referenced by Defiler(), Enfiler(), and FilePleine().
Typedef Documentation
typedef struct TFile BC
Function Documentation
char Defiler (BC * bc)
Definition at line 26 of file Buffer_Circ.c.
References TFile::corps, TailleFile, and TFile::Tete.
Referenced by main().
void Enfiler (BC * bc, char c)
Definition at line 35 of file Buffer_Circ.c.
References TFile::corps, TFile::Queue, and TailleFile.
int FilePleine (BC * bc)
Definition at line 21 of file Buffer_Circ.c.
References TFile::Queue, TailleFile, and TFile::Tete.
int FileVide (BC * bc)
Definition at line 16 of file Buffer_Circ.c.
References TFile::Queue, and TFile::Tete.
Referenced by main().
void InitBC (BC * bc)
Definition at line 11 of file Buffer_Circ.c.
References TFile::Queue, and TFile::Tete.
Referenced by main().