My Project: HAL/Flash.h File Reference
Flash.h File Reference
Functions
void Init_SPI ()
void FLASH_READ_PAGE (ADDRESS, PAGE *)
HAL INIT SPI function.
void FLASH_WRITE_PAGE (ADDRESS, PAGE *)
HAL write functions API.
BYTE READ_STATUS ()
HAL Read Status function.
void BULK_ERASE ()
HAL Bulk Erase function.
void SOFTWARE_RESET ()
HAL Software reset function.
void READ_ID ()
void InitPage (PAGE *p)
void RechercheDernierePageStockee (ADDRESS *DernierePageStockee)
Function Documentation
void BULK_ERASE ()
HAL Bulk Erase function.
Select the device
FLASH_CS low
Write Enable
0xC7 - BULK ERASE ... nothing left on the chip !
Deselect the device when finished
FLASH_CS HIGH
Definition at line 227 of file Flash.c.
References SPI_BE_CMD, SPI_WREN_CMD, and SPITXDATA.
void FLASH_READ_PAGE (ADDRESS Ad, PAGE * p)
HAL INIT SPI function.
HAL read functions API
FLASH_READ - HAL read function
input : Ad system address to be used p Pointer to the data buffer where to store the read data
Page address (Ad*512)
Select the device
FLASH_CS low
Send the command
0x13 - Write command to UCB0TXBUF (SPI Buffer)
Send the 4-byte address
Send Dummy
Read the data, store it to Page STRUCT
Deselect the device when finished
FLASH_CS HIGH
Parameters
p Page to be used Pointer to the data buffer containing data to be written
Definition at line 91 of file Flash.c.
References PAGESIZE, SPI_READ_4B_CMD, SPIRXDATA, and SPITXDATA.
Referenced by RechercheDernierePageStockee().
void FLASH_WRITE_PAGE (ADDRESS Ad, PAGE * p)
HAL write functions API.
FLASH_WRITE - HAL write function
input :
Parameters
Ad system address to be used
p Pointer to the data buffer where to store the written data
Page address (Ad*512)
Write Enable
FLASH_CS low
FLASH_CS HIGH
Read status and untill WREN OK
FLASH_CS low
Send Read Status Register CMD
Send Dummy
FLASH_CS HIGH
Send the read command
FLASH_CS low
0x12 - Write command to UCB0TXBUF (SPI Buffer)
Send the 4-byte address
Deselect the device when finished
FLASH_CS HIGH
Parameters
p Page to be used Pointer to the data buffer containing data to be written
Definition at line 143 of file Flash.c.
References PAGESIZE, SPI_PP_4B_CMD, SPI_RDSR_CMD, SPI_WREN_CMD, SPIRXDATA, and SPITXDATA.
Referenced by main().
void Init_SPI ()
slld_hal.h - HAL Header file for Spansion SPI-flash Low Level Driver
public function prototypes
INIT_SPI - HAL INIT SPI function
Select eUSCI Pin Function
Select eUSCI Pin Function
Put state machine in reset
4-pin, 8-bit, SPI master CKPH = 0 CKPL=0 , MSB
SMCLK = 4MHz - No prescaler
Initialize USCI state machine
Definition at line 65 of file Flash.c.
Referenced by Init_HAL().
void InitPage (PAGE * p)
Definition at line 290 of file Flash.c.
References PAGE::NbTrame, and PAGE::Statut.
Referenced by main().
void READ_ID ()
Select the device
FLASH_CS low
Send the command
Write command to UCB0TXBUF (SPI Buffer)
Send the 4-byte address
Send Dummy
Deselect the device when finished
FLASH_CS HIGH
Definition at line 257 of file Flash.c.
References SPI_RDID_9F_CMD, and SPITXDATA.
BYTE READ_STATUS ()
HAL Read Status function.
Select the device
FLASH_CS low
05h - Send Read Status Register CMD
Send Dummy
Deselect the device when finished
FLASH_CS HIGH
Definition at line 206 of file Flash.c.
References SPI_RDSR_CMD, SPIRXDATA, and SPITXDATA.
void RechercheDernierePageStockee (ADDRESS * DernierePageStockee)
Definition at line 298 of file Flash.c.
References FLASH_READ_PAGE(), PAGE::NbTrame, and Page_Travail.
Referenced by main().
void SOFTWARE_RESET ()
HAL Software reset function.
Select the device
FLASH_CS low
0xF0 Complete memory erase
Deselect the device when finished
FLASH_CS HIGH
Definition at line 244 of file Flash.c.
References SPI_SOFTWARE_RESET, and SPITXDATA.