My Project: HAL/GPS.h File Reference
GPS.h File Reference
Functions
void resetDataGPSRegister (DataRegister *)
void initGPS ()
void TableInit (short *tableau, unsigned int cases)
short atos (char input)
short TabletoShort (short *Input, unsigned int Taille)
SBYTE TabletoSBYTE (short *Input, unsigned int Taille)
void ReadSentence (char *Sentence, DataRegister *InputReg)
BOOL MakeData (char *buffer, DataRegister *InputReg, BYTE *InputTrame)
void MakeTrame (BYTE *Trame, DataRegister *GPSRegister)
Function Documentation
short atos (char input)
Definition at line 62 of file GPS.c.
Referenced by ReadSentence().
void initGPS ()
Definition at line 11 of file GPS.c.
References TransmitDataGPS().
BOOL MakeData (char * buffer, DataRegister * InputReg, BYTE * InputTrame)
Definition at line 473 of file GPS.c.
References FALSE, MakeTrame(), ReadSentence(), resetDataGPSRegister(), and TRUE.
void MakeTrame (BYTE * Trame, DataRegister * GPSRegister)
Definition at line 373 of file GPS.c.
References Calendar::Annee, DataRegister::DA, Calendar::Heure, DataRegister::HH, Calendar::JourSemaine, MajRTC(), Calendar::Minute, Calendar::Mois, DataRegister::MTE, DataRegister::MTH, Calendar::NumeroJour, Calendar::Seconde, DataRegister::SS, startRTC(), and DataRegister::YY.
Referenced by MakeData().
void ReadSentence (char * Sentence, DataRegister * InputReg)
Definition at line 103 of file GPS.c.
References atos(), Azimuth, DATE, EW, FALSE, FixStatus, GEOIDALESEP, HDOP, Latitude, Longitude, MSLALT, NBRSat, NS, PDOP, TableInit(), TabletoSBYTE(), TabletoShort(), TIME, TRUE, VDOP, and Vitesse.
Referenced by MakeData().
void resetDataGPSRegister (DataRegister *)
Definition at line 21 of file GPS.c.
References FALSE.
Referenced by MakeData().
void TableInit (short * tableau, unsigned int cases)
Definition at line 53 of file GPS.c.
Referenced by ReadSentence().
SBYTE TabletoSBYTE (short * Input, unsigned int Taille)
Definition at line 85 of file GPS.c.
Referenced by ReadSentence().
short TabletoShort (short * Input, unsigned int Taille)
Definition at line 67 of file GPS.c.
Referenced by ReadSentence().