My Project: HAL/HAL.h File Reference
HAL.h File Reference
Macros
#define OFS_CSCTL0 (0x0000) /* CS Control Register 0 */
#define OFS_CSCTL1 (0x0002) /* CS Control Register 1 */
#define OFS_CSCTL2 (0x0004) /* CS Control Register 2 */
#define OFS_CSCTL3 (0x0006) /* CS Control Register 3 */
#define OFS_CSCTL4 (0x0008) /* CS Control Register 4 */
#define OFS_CSCTL5 (0x000A) /* CS Control Register 5 */
#define OFS_CSCTL6 (0x000C) /* CS Control Register 6 */
#define HWREG32(x) (*((volatile uint32_t *)((uint16_t)x)))
#define HWREG16(x) (*((volatile uint16_t *)((uint16_t)x)))
#define HWREG8(x) (*((volatile uint8_t *)((uint16_t)x)))
Functions
void Init_HAL ()
void InitClockSystem ()
void InitUARTGPS ()
void InitUARTRF ()
void InitSPIMem ()
void InitRTC ()
void InitADC ()
void InitIO ()
void StatusLedToggle ()
void ModifUARTRF ()
void MajRTC (Calendar)
Calendar getRTCTime ()
void setAlarm (ConfLoggeur)
void startRTC ()
void SleepCPU ()
void WakeGPS ()
void SleepGPS ()
void EnableReceiveDataGPS ()
void TransmitDataGPS (char *)
char readGPSUART ()
void GetGPSFIX ()
void EnableReceiveDataRF ()
void TransmitDataRF (char *)
void SleepRF ()
void ConfigModeRF ()
void SendCharRF (char c)
void WDT_Enable ()
void WDT_Disable ()
Activate the Watchdog.
void WDT_Init ()
Remove the Watchdog.
BOOL WDT_FIN ()
Initialize the timer.
void SleepFor (unsigned int Seconds)
Check if program aborted due to Watchdog.
Macro Definition Documentation
#define HWREG16 (x) (*((volatile uint16_t *)((uint16_t)x)))
Definition at line 60 of file HAL.h.
Referenced by InitRTC().
#define HWREG32 (x) (*((volatile uint32_t *)((uint16_t)x)))
______________ Macros to access registers
Definition at line 58 of file HAL.h.
#define HWREG8 (x) (*((volatile uint8_t *)((uint16_t)x)))
Definition at line 62 of file HAL.h.
Referenced by InitRTC().
#define OFS_CSCTL0 (0x0000) /* CS Control Register 0 */
______________ Offset index for RTC Control registers
Definition at line 49 of file HAL.h.
#define OFS_CSCTL1 (0x0002) /* CS Control Register 1 */
Definition at line 50 of file HAL.h.
#define OFS_CSCTL2 (0x0004) /* CS Control Register 2 */
Definition at line 51 of file HAL.h.
#define OFS_CSCTL3 (0x0006) /* CS Control Register 3 */
Definition at line 52 of file HAL.h.
#define OFS_CSCTL4 (0x0008) /* CS Control Register 4 */
Definition at line 53 of file HAL.h.
Referenced by InitRTC().
#define OFS_CSCTL5 (0x000A) /* CS Control Register 5 */
Definition at line 54 of file HAL.h.
Referenced by InitRTC().
#define OFS_CSCTL6 (0x000C) /* CS Control Register 6 */
Definition at line 55 of file HAL.h.
Function Documentation
void ConfigModeRF ()
Definition at line 256 of file HAL.c.
void EnableReceiveDataGPS ()
Definition at line 162 of file HAL.c.
void EnableReceiveDataRF ()
_______________RF
Definition at line 222 of file HAL.c.
Referenced by main().
void GetGPSFIX ()
Definition at line 157 of file HAL.c.
Referenced by main().
Calendar getRTCTime ()
Returns the Calendar Time stored in the Calendar registers of the RTC.
This function returns the current Calendar time in the form of a Calendar structure.
Returns
A Calendar structure containing the current time.
Definition at line 347 of file HAL.c.
References Calendar::Annee, Calendar::Heure, Calendar::JourSemaine, Calendar::Minute, Calendar::Mois, Calendar::NumeroJour, and Calendar::Seconde.
Referenced by main().
void Init_HAL ()
Hardware Abstraction Layer Mars 2013
*********** LOW LEVEL
Definition at line 18 of file HAL.c.
References Init_SPI(), InitClockSystem(), InitIO(), InitUARTGPS(), and InitUARTRF().
Referenced by main().
void InitADC ()
void InitClockSystem ()
_______________________________ Basic MSP430FR5739 Init. Functions
Initializes all the clocks (MCLK/SMCLK/ACLK/LFXT1)
Init RTC Oscillator (32768Hz)
Init DCO (Digitally Controlled Oscillator @8MHz)
MCLK = DCOCLK = 8MHz
SMCLK = DCOCLK/2 = 4MHz
ACLK = VLOCLK/4 = 3000Hz
Definition at line 38 of file HAL.c.
Referenced by Init_HAL().
void InitIO ()
void InitIO() Initializes all the IOs
Definition at line 51 of file HAL.c.
Referenced by Init_HAL().
void InitRTC ()
Initialize RTC_B Module
Definition at line 269 of file HAL.c.
References HWREG16, HWREG8, OFS_CSCTL4, and OFS_CSCTL5.
void InitSPIMem ()
void InitUARTGPS ()
Definition at line 132 of file HAL.c.
Referenced by Init_HAL().
void InitUARTRF ()
Definition at line 195 of file HAL.c.
Referenced by Init_HAL().
void MajRTC (Calendar)
_______________Real Time Clock
Definition at line 309 of file HAL.c.
References Calendar::Annee, Calendar::Heure, Calendar::JourSemaine, Calendar::Minute, Calendar::Mois, Calendar::NumeroJour, and Calendar::Seconde.
Referenced by MakeTrame().
void ModifUARTRF ()
Definition at line 210 of file HAL.c.
char readGPSUART ()
Definition at line 168 of file HAL.c.
void SendCharRF (char c)
Definition at line 230 of file HAL.c.
void setAlarm (ConfLoggeur)
Definition at line 323 of file HAL.c.
void SleepCPU ()
Definition at line 377 of file HAL.c.
void SleepFor (unsigned int Seconds)
Check if program aborted due to Watchdog.
Definition at line 407 of file HAL.c.
void SleepGPS ()
void SleepRF ()
Definition at line 251 of file HAL.c.
Referenced by main().
void startRTC ()
Definition at line 364 of file HAL.c.
Referenced by MakeTrame().
void StatusLedToggle ()
Definition at line 118 of file HAL.c.
void TransmitDataGPS (char *)
Definition at line 173 of file HAL.c.
Referenced by initGPS().
void TransmitDataRF (char *)
Definition at line 238 of file HAL.c.
References pRFTXTrame.
void WakeGPS ()
_______________GPS
Definition at line 148 of file HAL.c.
Referenced by main().
void WDT_Disable ()
Activate the Watchdog.
Remove the Watchdog
Definition at line 392 of file HAL.c.
Referenced by main().
void WDT_Enable ()
_______________Watchdog Timer
BOOL WDT_FIN ()
Initialize the timer.
Definition at line 403 of file HAL.c.
References WDT_STATUS.
Referenced by main().
void WDT_Init ()
Remove the Watchdog.
Initialize the timer
Definition at line 396 of file HAL.c.