My Project: HAL/HAL.c File Reference
HAL.c File Reference
#include "TYPEDEF.h"
#include <msp430fr5739.h>
#include "HAL.h"
Functions
void Init_HAL ()
void InitClockSystem ()
void InitIO ()
void StatusLedToggle ()
void InitUARTGPS ()
void WakeGPS ()
void SleepGPS (BOOL *init)
void GetGPSFIX ()
void EnableReceiveDataGPS ()
char readGPSUART ()
void TransmitDataGPS (char *pdata)
void InitUARTRF ()
void ModifUARTRF ()
void EnableReceiveDataRF ()
void TransmitChar (char c)
void TransmitDataRF (char *p)
void SleepRF ()
void ConfigModeRF ()
void InitRTC ()
void MajRTC (Calendar GPSCurrentTime)
void setAlarm (ConfLoggeur cfg)
Calendar getRTCTime ()
void startRTC ()
void SleepCPU ()
void WDT_Enable (unsigned int Seconds)
Activate Countdown Timer for.
void WDT_Disable ()
Activate the Watchdog.
void WDT_Init ()
Remove the Watchdog.
BOOL WDT_FIN ()
Initialize the timer.
void SleepFor (unsigned int Seconds)
Check if program aborted due to Watchdog.
Variables
char * pRFTXTrame
char pGPSTXTrame
char RFTXTrameLen
Function Documentation
void ConfigModeRF ()
Definition at line 249 of file HAL.c.
void EnableReceiveDataGPS ()
Definition at line 158 of file HAL.c.
void EnableReceiveDataRF ()
_______________RF
Definition at line 218 of file HAL.c.
Referenced by main().
void GetGPSFIX ()
Definition at line 153 of file HAL.c.
Referenced by main().
Calendar getRTCTime ()
Returns the Calendar Time stored in the Calendar registers of the RTC.
This function returns the current Calendar time in the form of a Calendar structure.
Returns
A Calendar structure containing the current time.
Definition at line 340 of file HAL.c.
References Calendar::Annee, Calendar::Heure, Calendar::JourSemaine, Calendar::Minute, Calendar::Mois, Calendar::NumeroJour, and Calendar::Seconde.
Referenced by main().
void Init_HAL ()
Hardware Abstraction Layer Mars 2013
*********** LOW LEVEL
Definition at line 18 of file HAL.c.
Referenced by main().
InitClockSystem ()
_______________________________ Basic MSP430FR5739 Init. Functions
Initializes all the clocks (MCLK/SMCLK/ACLK/LFXT1)
Init RTC Oscillator (32768Hz)
Init DCO (Digitally Controlled Oscillator @8MHz)
MCLK = DCOCLK = 8MHz
SMCLK = DCOCLK/2 = 4MHz
ACLK = VLOCLK/4 = 3000Hz
Definition at line 34 of file HAL.c.
void InitIO ()
void InitIO() Initializes all the IOs
Definition at line 47 of file HAL.c.
void InitRTC ()
Initialize RTC_B Module
Definition at line 262 of file HAL.c.
References HWREG16, HWREG8, OFS_CSCTL4, and OFS_CSCTL5.
void InitUARTGPS ()
Definition at line 128 of file HAL.c.
void InitUARTRF ()
Definition at line 191 of file HAL.c.
void MajRTC (Calendar)
_______________Real Time Clock
Definition at line 302 of file HAL.c.
References Calendar::Annee, Calendar::Heure, Calendar::JourSemaine, Calendar::Minute, Calendar::Mois, Calendar::NumeroJour, and Calendar::Seconde.
Referenced by MakeTrame().
void ModifUARTRF ()
Definition at line 206 of file HAL.c.
char readGPSUART ()
Definition at line 164 of file HAL.c.
void setAlarm (ConfLoggeur cfg)
Definition at line 316 of file HAL.c.
void SleepCPU ()
Definition at line 370 of file HAL.c.
void SleepFor (unsigned int Seconds)
Check if program aborted due to Watchdog.
Definition at line 400 of file HAL.c.
void SleepGPS (BOOL * init)
Definition at line 148 of file HAL.c.
References FALSE.
Referenced by main().
void SleepRF ()
Definition at line 244 of file HAL.c.
Referenced by main().
void startRTC ()
Definition at line 357 of file HAL.c.
Referenced by MakeTrame().
void StatusLedToggle ()
Definition at line 114 of file HAL.c.
void TransmitChar (char c)
Definition at line 226 of file HAL.c.
void TransmitDataGPS (char * pdata)
Definition at line 169 of file HAL.c.
Referenced by initGPS().
void TransmitDataRF (char * p)
Definition at line 231 of file HAL.c.
References pRFTXTrame.
void WakeGPS ()
_______________GPS
Definition at line 144 of file HAL.c.
Referenced by main().
void WDT_Disable ()
Activate the Watchdog.
Remove the Watchdog
Definition at line 385 of file HAL.c.
Referenced by main().
void WDT_Enable (unsigned int Seconds)
Activate Countdown Timer for.
Definition at line 380 of file HAL.c.
Referenced by main().
BOOL WDT_FIN ()
Initialize the timer.
Check if program aborted due to Watchdog
Definition at line 396 of file HAL.c.
Referenced by main().
void WDT_Init ()
Remove the Watchdog.
Initialize the timer
Definition at line 389 of file HAL.c.
Variable Documentation
char pGPSTXTrame
char* pRFTXTrame
Hardware Abstraction Layer Mars 2013
Referenced by TransmitDataRF().
char RFTXTrameLen