My Project: main.c File Reference
main.c File Reference
#include "main.h"
Functions
int main (void)
Variables
BYTE * Trame_Travail
BYTE * Trame_GGA
BYTE * Trame_GSA
BYTE * Trame_RMC
BYTE * Trame_VTG
BYTE Trame_Recues
BYTE VBat
BYTE TempC
BYTE Status
BYTE EtatAEF
BYTE Acquisition_OK
BYTE CompteurAcquisitionGPS
BYTE iCpt
BYTE Reveil_Urgent
Function Documentation
int main (void)
Definition at line 24 of file main.c.
References Acquisition_OK, AcquisitionGPS, BC_GPS, BC_RF, CommunicationRF, CompteurAcquisitionGPS, Defiler(), DerniereHeureAcquisitionGPS, DernierePageStockee, EnableReceiveDataRF(), EtatAEF, FALSE, FileVide(), FLASH_WRITE_PAGE(), GetGPSFIX(), getRTCTime(), iCpt, Init_HAL(), InitBC(), InitPage(), PAGE::NbTrame, Page_Courante, RechercheDernierePageStockee(), Reveil_Urgent, SleepGPS(), SleepRF(), PAGE::TR, TRAME_NMEA, Trame_Recues, Trame_Travail, Trame_ZIP, TRUE, WakeGPS(), WDT_Disable(), WDT_Enable(), and WDT_FIN().
Variable Documentation
BYTE Acquisition_OK
Definition at line 18 of file main.c.
Referenced by main().
BYTE CompteurAcquisitionGPS
Definition at line 19 of file main.c.
Referenced by main().
BYTE EtatAEF
Definition at line 17 of file main.c.
Referenced by main().
BYTE iCpt
Definition at line 20 of file main.c.
Referenced by main().
BYTE Reveil_Urgent
Definition at line 21 of file main.c.
Referenced by main().
BYTE Status
Definition at line 15 of file main.c.
BYTE TempC
Definition at line 13 of file main.c.
BYTE* Trame_GGA
Definition at line 6 of file main.c.
BYTE* Trame_GSA
Definition at line 7 of file main.c.
BYTE Trame_Recues
Definition at line 11 of file main.c.
Referenced by main().
BYTE* Trame_RMC
Definition at line 8 of file main.c.
BYTE* Trame_Travail
Definition at line 4 of file main.c.
Referenced by main().
BYTE* Trame_VTG
Definition at line 9 of file main.c.
BYTE VBat
Definition at line 12 of file main.c.