My Project: HAL/slld_HAL.c File Reference
slld_HAL.c File Reference
#include <msp430fr5739.h>
#include <stdio.h>
#include "TYPEDEF.h"
#include "slld.h"
#include "slld_hal.h"
Macros
#define SPITXDATA UCB0TXBUF
#define SPIRXDATA UCB0RXBUF
Functions
void INIT_SPI ()
void FLASH_READ_PAGE (ADDRESS Ad, PAGE *p)
HAL INIT SPI function.
void FLASH_WRITE_PAGE (ADDRESS Ad, PAGE *p)
HAL write functions API.
BYTE READ_STATUS ()
HAL Read Status function.
void BULK_ERASE ()
HAL Sector Erase fnction.
void SOFTWARE_RESET ()
HAL Software reset function.
void READ_ID ()
Macro Definition Documentation
#define SPIRXDATA UCB0RXBUF
Definition at line 59 of file slld_HAL.c.
Referenced by FLASH_READ_PAGE(), FLASH_WRITE_PAGE(), and READ_STATUS().
#define SPITXDATA UCB0TXBUF
Library inspired from the official SPANSION Low Level Driver (SLLD) for SPI FLASH PFISTER Frédéric - April 2013 pfist.nosp@m.er.f.nosp@m.red@g.nosp@m.mail.nosp@m..com This has been used and tested with SPANSION S25FL256S and S25FL512S And the MCU was a MSP430FR5739
slld_hal_example.c - SLLD Hardware Abstraction Layer example Code
Requirements per PCB Design and Datasheet P2.2 - FLASH_CLK P1.6 - FLASH_SIMO P1.7 - FLASH_SOMI P3.7 - FLASH_CS Mode 3 with CPOL = 1 and, CPHA = 1 CS is enabled when Low RX Buffer : UCB0RXBUF TX Buffer : UCB0TXBUF
Definition at line 58 of file slld_HAL.c.
Referenced by BULK_ERASE(), FLASH_READ_PAGE(), FLASH_WRITE_PAGE(), READ_ID(), READ_STATUS(), and SOFTWARE_RESET().
Function Documentation
void BULK_ERASE ()
HAL Sector Erase fnction.
HAL Bulk Erase function.
Select the device
FLASH_CS low
Write Enable
0xC7 - BULK ERASE ... nothing left on the chip !
Deselect the device when finished
FLASH_CS HIGH
Definition at line 226 of file slld_HAL.c.
References SPI_BE_CMD, SPI_WREN_CMD, and SPITXDATA.
void FLASH_READ_PAGE (ADDRESS Ad, PAGE * p)
HAL INIT SPI function.
FLASH_READ - HAL read function
input : Ad system address to be used p Pointer to the data buffer where to store the read data
Page address (Ad*512)
Select the device
FLASH_CS low
Send the command
0x13 - Write command to UCB0TXBUF (SPI Buffer)
Send the 4-byte address
Send Dummy
Read the data, store it to Page STRUCT
Deselect the device when finished
FLASH_CS HIGH
Parameters
p Page to be used Pointer to the data buffer containing data to be written
Definition at line 90 of file slld_HAL.c.
References PAGESIZE, SPI_READ_4B_CMD, SPIRXDATA, and SPITXDATA.
Referenced by main().
void FLASH_WRITE_PAGE (ADDRESS Ad, PAGE * p)
HAL write functions API.
FLASH_WRITE - HAL write function
input :
Parameters
Ad system address to be used
p Pointer to the data buffer where to store the written data
Page address (Ad*512)
Write Enable
FLASH_CS low
FLASH_CS HIGH
Read status and untill WREN OK
FLASH_CS low
Send Read Status Register CMD
Send Dummy
FLASH_CS HIGH
Send the read command
FLASH_CS low
0x12 - Write command to UCB0TXBUF (SPI Buffer)
Send the 4-byte address
Deselect the device when finished
FLASH_CS HIGH
Parameters
p Page to be used Pointer to the data buffer containing data to be written
Definition at line 142 of file slld_HAL.c.
References PAGESIZE, SPI_PP_4B_CMD, SPI_RDSR_CMD, SPI_WREN_CMD, SPIRXDATA, and SPITXDATA.
Referenced by main().
void INIT_SPI ()
INIT_SPI - HAL INIT SPI function
Select eUSCI Pin Function
Select eUSCI Pin Function
Put state machine in reset
4-pin, 8-bit, SPI master CKPH = 0 CKPL=0 , MSB
SMCLK = 4MHz - No prescaler
Initialize USCI state machine
Definition at line 64 of file slld_HAL.c.
Referenced by main().
void READ_ID ()
Select the device
FLASH_CS low
Send the command
Write command to UCB0TXBUF (SPI Buffer)
Send the 4-byte address
Send Dummy
Deselect the device when finished
FLASH_CS HIGH
Definition at line 256 of file slld_HAL.c.
References SPI_RDID_9F_CMD, and SPITXDATA.
BYTE READ_STATUS ()
HAL Read Status function.
Select the device
FLASH_CS low
05h - Send Read Status Register CMD
Send Dummy
Deselect the device when finished
FLASH_CS HIGH
Definition at line 205 of file slld_HAL.c.
References SPI_RDSR_CMD, SPIRXDATA, and SPITXDATA.
Referenced by main().
void SOFTWARE_RESET ()
HAL Software reset function.
Select the device
FLASH_CS low
0xF0 Complete memory erase
Deselect the device when finished
FLASH_CS HIGH
Definition at line 243 of file slld_HAL.c.
References SPI_SOFTWARE_RESET, and SPITXDATA.
Referenced by main().